routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $deadline = \App\deadline::where('status','=',1)->first();
    return redirect()->action('AuthController@login');
});

Route::get('/Login', 'AuthController@login')->name('login');
Route::post('/postlogin', 'AuthController@postlogin');
Route::get('/Logout', 'AuthController@logout');

Route::group(['middleware' => ['auth','checkRole:admin']], function () {
    Route::get('/Dashboard-Admin', 'DashboardController@admin');
    Route::get('/Mahasiswa', 'MahasiswaController@index');
    Route::post('/Mahasiswa/create', 'MahasiswaController@create');
    Route::get('/Mahasiswa/edit/{NIM}', 'MahasiswaController@edit');
    Route::post('/Mahasiswa/update/{NIM}', 'MahasiswaController@update');
    Route::get('/Mahasiswa/delete/{NIM}', 'MahasiswaController@delete');
    Route::get('/Mahasiswa/CreateUser', 'MahasiswaController@createUserMahasiswa');

    Route::get('/Dosen/Create', 'DosenController@create');
    Route::get('/Dosen/edit/{kode_dosen}', 'DosenController@edit');
    Route::post('/Dosen/{kode_dosen}/updateAdmin', 'DosenController@updateAdmin');
    Route::get('/Dosen/delete/{kode_dosen}', 'DosenController@delete');
    Route::post('/Dosen/Store', 'DosenController@store');
    Route::get('/Dosen/CreateUser', 'DosenController@createUserDosen');

    Route::resource('BAB', 'BabController');
    Route::resource('SubBab', 'SubBabController');
    Route::resource('Minggu-Bimbingan', 'MinggubimbinganController');
    Route::resource('Deadline', 'DeadlineController');
    Route::resource('Poin-Penilaian', 'PoinPenilaianController');
    Route::resource('Poin-Penilaian-Laporan', 'PoinPenilaianLaporanController');
    Route::resource('Jadwal-Sidang', 'JadwalSidangController');
});

Route::group(['middleware' => ['auth','checkRole:mhs']], function () {
    Route::get('/Mahasiswa/Beranda', 'DashboardController@mahasiswa');
    Route::get('/Mahasiswa/Profile', 'MahasiswaController@profile');
    Route::post('/Mahasiswa/{NIM}/update', 'MahasiswaController@update'); 
    Route::post('/Mahasiswa/changePassword', 'MahasiswaController@changePassword');

    Route::post('/Proposal/Store/Finalisasi', 'proposal_taController@storefinalisasi');

    Route::get('/Proposal/TA/R0', 'proposal_taController@createR0');
    Route::get('/Proposal/TA/R1', 'proposal_taController@createR1');
    Route::post('/Proposal/Store/DataProposal', 'proposal_taController@storeDataProposal');
    Route::post('/Proposal/Store/Abstrak', 'proposal_taController@storeAbstrak');
    Route::post('/Proposal/Store/Pendahuluan', 'proposal_taController@storePendahuluan');
    Route::post('/Proposal/Store/TinjauanPustaka', 'proposal_taController@storeTinjauanPustaka');
    Route::post('/Proposal/Store/MetodePelaksanaan', 'proposal_taController@storeMetodePelaksanaan');
    Route::post('/Proposal/Store/BiayaJadwal', 'proposal_taController@storeBiayaJadwal');
    Route::post('/Proposal/Store/DaftarPustaka', 'proposal_taController@storeDaftarPustaka');
    Route::post('/Proposal/Store/JustifikasiAnggaran', 'proposal_taController@storeJustifikasiAnggaran');
    Route::post('/Proposal/Store/UploadFile', 'proposal_taController@storeUploadFile');
    Route::post('/Proposal/Store/GambaranTeknologi', 'proposal_taController@storeGambaranTeknologi');

    Route::get('/Laporan/TA', 'laporanTAController@create');
    Route::post('/LaporanTA/Store', 'laporanTAController@store');

    Route::get('Bimbingan', 'BimbinganController@index');
    Route::get('Bimbingan/create', 'BimbinganController@create');
    Route::post('Bimbingan/store', 'BimbinganController@store');

    Route::resource('Paper', 'paperController');
    
});

Route::group(['middleware' => ['auth','checkRole:dsn']], function () {
    Route::get('/Dosen/Beranda', 'DosenController@index');
    Route::get('/Dosen/Profile', 'DosenController@profile');
    Route::post('/Dosen/{kode_dosen}/update', 'DosenController@update');
    Route::post('/Dosen/changePassword', 'DosenController@changePassword');
    Route::get('/Bimbingan/Verifikasi', 'BimbinganController@verifikasi');
    Route::get('/Bimbingan/Rekap', 'BimbinganController@rekap');
    Route::get('/Bimbingan/ListVerifikasi', 'BimbinganController@ListVerifikasi');
    Route::post('/Bimbingan/saveBimbingan', 'BimbinganController@saveBimbingan');
    //// laporan ta
    Route::get('/Laporan/Penilaian/List-Mahasiswa', 'laporanTAController@listMahasiswa');
    Route::get('/Laporan/Penilaian/{nim}', 'laporanTAController@penilaianLaporan');
    Route::post('/Laporan/Penilaian/simpan', 'laporanTAController@saveNilaiLaporan');
    Route::post('/Laporan/Revisi/simpan', 'laporanTAController@saveRevisiLaporan');
    Route::post('/Laporan/Revisi/finalisasi', 'laporanTAController@finalisasiRevisiLaporan');
    Route::get('/Laporan/Nilai/List-Mahasiswa', 'laporanTAController@listMahasiswapanitia');
    Route::get('/Laporan/Download/{nama}', 'laporanTAController@downloadfile');
    Route::post('/Unlock/Laporan', 'laporanTAController@unlocknilailaporan');
    Route::get('/Laporan/Nilai/{nim}', 'laporanTAController@detailNilaiLaporan');
    Route::get('/Laporan/Penilaian/Panitia/{nim}/{kode_dosen}', 'laporanTAController@penilaianLaporanPanitia');
    ////sidang ta
    Route::get('/SidangTA/Penilaian/List-Mahasiswa', 'sidangTAController@listMahasiswa');
    Route::get('/SidangTA/Penilaian/{nim}', 'sidangTAController@penilaianSidangTA');
    Route::post('/Laporan/Penilaian/SidangTA/simpan', 'sidangTAController@saveNilaiSidang');
    Route::post('/SidangTA/finalisasi', 'sidangTAController@finalisasiNilaiSidang');
    Route::get('/SidangTA/Nilai-Akhir/{nim}', 'sidangTAController@nilaiSidangAkhir');
    Route::get('/SidangTA/Nilai/List-Mahasiswa', 'sidangTAController@listMahasiswapanitia');
    Route::get('/SidangTA/Penilaian/Panitia/{nim}/{kode_dosen}', 'sidangTAController@penilaianSidangTAPanitia');

    //NIlai PKM publikasi
    Route::resource('/Nilai-PKM-Publikasi', 'nilaiPKMPublikasiController');

    //Paper
    Route::get('/Mahasiswa-Paper', 'paperController@listMahasiswa');
    Route::post('/Paper/saveStatusPaper', 'paperController@saveStatusPaper');
    
});

app/paper.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class paper extends Model
{
    protected $table = 'paper';
    protected $fillable = ['nim','judul','bukti','paper','status'];

    public function mahasiswa(){
        return $this->hasOne('App\Mahasiswa','nim','nim');
    }
}

app/Http/Controllers/paperController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\paper;
use Auth;
class paperController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $paper = paper::where('nim','=',Auth::user()->username)->get();
        return view('Paper.index',compact('paper'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $paper = new paper;
        $paper->nim = $request->nim;
        $paper->judul = $request->judul;
        $paper->save();
        
        if ($request->hasFile('bukti')) {
            $imgName = generateNamaBukti(Auth::user()->username,$request->file('bukti')->getClientOriginalExtension());
            $file = $request->file('bukti');
            $file->storeAs('public/Bukti_Pembayaran', $imgName);
            
            
            $paper->bukti = $imgName;
            $paper->save();

            if(!$paper){
                return redirect()->back()->with('gagal','Gagal Upload Diubah/Disimpan');
            }
        }

        if ($request->hasFile('paper')) {
            $imgName = generateNamaPaper(Auth::user()->username,$request->file('paper')->getClientOriginalExtension());
            $file = $request->file('paper');
            $file->storeAs('public/Paper', $imgName);
            
            
            $paper->paper = $imgName;
            $paper->save();

            if(!$paper){
                return redirect()->back()->with('gagal','Gagal Upload Diubah/Disimpan');
            }
        } 
        return redirect('/Paper')->with('sukses','Data Berhasil Disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $paper = paper::find($id);
        return view('Paper.edit',compact('paper'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $paper = paper::find($id);
        $paper->nim = $request->nim;
        $paper->judul = $request->judul;
        $paper->save();

        if ($request->hasFile('bukti')) {
            $imgName = generateNamaBukti(Auth::user()->username,$request->file('bukti')->getClientOriginalExtension());
            $file = $request->file('bukti');
            $file->storeAs('public/Bukti_Pembayaran', $imgName);
            
            $paper = paper::find($id);
            $paper->bukti = $imgName;
            $paper->save();

            if(!$paper){
                return redirect()->back()->with('gagal','Gagal Upload Diubah/Disimpan');
            }
        }

        if ($request->hasFile('paper')) {
            $imgName = generateNamaPaper(Auth::user()->username,$request->file('paper')->getClientOriginalExtension());
            $file = $request->file('paper');
            $file->storeAs('public/Paper', $imgName);
            
            $paper = paper::find($id);
            $paper->paper = $imgName;
            $paper->save();

            if(!$paper){
                return redirect()->back()->with('gagal','Gagal Upload Diubah/Disimpan');
            }
        } 
        return redirect('/Paper')->with('sukses','Data Berhasil Disimpan');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $paper = \App\paper::find($id);
        $paper->delete();
        return redirect('/Paper')->with('sukses','Data Berhasil Dihapus');
    }

    public function listMahasiswa(){
        $paper = paper::all();
        return view('Paper.listMahasiswa',compact('paper'));
    }

    public function saveStatusPaper(Request $request){
        $paper = paper::find($request->id);
        $paper->status = 1;
        $paper->save();

        if ($paper->save()) {
            echo "Success";
        }
    }
}

resources/views/Paper/edit.blade.php
@extends('Layout.master')

@section('title','Edit Paper')

@section('navbar')
<!-- Navbar -->
<nav class="main-header navbar navbar-expand bg-primary navbar-dark ">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="{{url('/Mahasiswa/Beranda')}}" class="nav-link">Beranda</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="{{url('/Mahasiswa/Profile')}}" class="nav-link">Ubah Profile</a>
    </li>
  </ul>

</nav>
<!-- /.navbar -->
@stop

@section('content')
@if (session('sukses'))
<div class="alert alert-success col-md-6 alert-fixed" role="alert" >
    {{session('sukses')}}
</div>
@elseif (session('gagal'))
<div class="alert alert-danger col-md-6 alert-fixed" role="alert" >
    {{session('gagal')}}
</div>
@endif

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Edit Upload Paper</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Edit</a></li>
                    <li class="breadcrumb-item active">Upload Paper</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class='col-md-12 col-xs-12'>

              <!-- ./Data Proposal -->    
              <div class="row">
                <div class="col-md-12">
                    <div class="card card-info card-outline">
                      <div class="card-header">
                        <h3 class="card-title">
                          Edit Upload Paper
                        </h3>
                          <!-- tools box -->
                          <div class="card-tools">
                            <button type="button" class="btn btn-tool btn-sm" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                                <i class="fa fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool btn-sm" data-widget="remove" data-toggle="tooltip" title="Remove">
                                <i class="fa fa-times"></i>
                            </button>
                          </div>
                          <!-- /. tools -->
                      </div>
                      <!-- /.card-header -->
                      <div class="card-body" style="display: block;">
                        <div class="row" style="margin-top:20px;">
                            <div class="col-8">
                                <form action="{{ route('Paper.update', $paper->id) }}" method="POST" enctype='multipart/form-data'>
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="PUT">  
                                    <input type="hidden" name="nim" value="{{auth()->user()->username}}">
                                    <div class="form-group">
                                        <label>Judul</label>
                                        <textarea name="judul" rows="5" class="form-control" required>{{$paper->judul}}</textarea>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputFile"> Abstrak Laporan Tugas Akhir Final (PDF) </label>
                                        <br>
                                        <span> Bukti Pembayaran (PDF)</span>
                                        <input type="file" name="bukti" accept=".pdf"  class="form-control">         
                                    </div> 
                                    <div class="form-group">
                                        <label for="exampleInputFile"> Abstrak Laporan Tugas Akhir Final (PDF) </label>
                                        <br>
                                        <span> Paper (PDF)</span>
                                        <input type="file" name="paper" accept=".pdf"  class="form-control">         
                                    </div>
                                    <button type="submit" class="btn btn-primary" value="Simpan"> Save changes</button>  
                                </form>
                            </div>
                        </div>
                      </div>
                    </div>
                    <!-- /.card -->          
                </div>
              <!-- /.col-->
              </div>
              <!-- ./row -->                  
            </div>
          </div>
    <!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
@stop

@push('scripts')
  
 

@endpush

resources/views/Paper/index.blade.php
@extends('Layout.master')

@section('title','Paper')

@section('navbar')
<!-- Navbar -->
<nav class="main-header navbar navbar-expand bg-primary navbar-dark ">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="{{url('/Mahasiswa/Beranda')}}" class="nav-link">Beranda</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="{{url('/Mahasiswa/Profile')}}" class="nav-link">Ubah Profile</a>
    </li>
  </ul>

</nav>
<!-- /.navbar -->
@stop

@section('content')
@if (session('sukses'))
<div class="alert alert-success col-md-6 alert-fixed" role="alert" >
    {{session('sukses')}}
</div>
@elseif (session('gagal'))
<div class="alert alert-danger col-md-6 alert-fixed" role="alert" >
    {{session('gagal')}}
</div>
@endif

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Upload Paper</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Upload Paper</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class='col-md-12 col-xs-12'>

              <!-- ./Data Proposal -->    
              <div class="row">
                <div class="col-md-12">
                    <div class="card card-info card-outline">
                      <div class="card-header">
                        <h3 class="card-title">
                          Upload Paper
                        </h3>
                          <!-- tools box -->
                          <div class="card-tools">
                            <button type="button" class="btn btn-tool btn-sm" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                                <i class="fa fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool btn-sm" data-widget="remove" data-toggle="tooltip" title="Remove">
                                <i class="fa fa-times"></i>
                            </button>
                          </div>
                          <!-- /. tools -->
                      </div>
                      <!-- /.card-header -->
                      <div class="card-body" style="display: block;">
                        <div class="row">                           
                            <div class="col-2 offset-1">
                                <!-- Button trigger modal -->
                                <button type="button" class="btn btn-primary float-right" data-toggle="modal" data-target="#exampleModal" style="margin-right:40px;">
                                    Tambah Paper
                                </button>
                            </div>              
                        </div>
                        <div class="row" style="margin-top:20px;">
                            <div class="col-md-12">
                                <table class="table table-hover table-responsive">
                                    <thead align='center' >
                                        <tr>
                                            <th>Judul </th>
                                            <th>Bukti Pembayaran Paper</th>
                                            <th>Paper</th>
                                            <th colspan="2">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($paper as $item)
                                            <tr>
                                                <td>{{$item->judul}}</td>
                                                <td><a href={{asset('storage/Bukti_Pembayaran/'.$item->bukti)}} class="btn btn-primary" target="_blank">Lihat Bukti</a></td>
                                                <td><a href={{asset('storage/Paper/'.$item->paper)}} class="btn btn-primary" target="_blank">Lihat Paper</a></td>
                                                <td><a href="{{ route('Paper.edit',$item->id) }}" class="btn btn-warning">Edit</a></td>
                                                <td>
                                                    <form action="{{ route('Paper.destroy', $item->id)}}" method="post">
                                                            <input type="hidden" name="_method" value="DELETE">                 
                                                            {{csrf_field()}}
                                                        <button class="btn btn-danger" type="submit" onclick="return confirm('Yakin anda akan menghapus data ini ?')">Delete</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                                
                            </div>
                        </div>
                      </div>
                    </div>
                    <!-- /.card -->          
                </div>
              <!-- /.col-->
              </div>
              <!-- ./row -->                  
            </div>
          </div>
    <!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Upload Paper</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-body">
            <form action="{{ route('Paper.store') }}" method="POST" enctype='multipart/form-data'>
                {{ csrf_field() }}
                <input type="hidden" name="nim" value="{{auth()->user()->username}}">
                <div class="form-group">
                    <label>Judul</label>
                    <textarea name="judul" rows="5" class="form-control" required></textarea>
                </div>
                <div class="form-group">
                    <label for="exampleInputFile"> Abstrak Laporan Tugas Akhir Final (PDF) </label>
                    <br>
                    <span> Bukti Pembayaran (PDF)</span>
                    <input type="file" name="bukti" accept=".pdf"  class="form-control">         
                </div> 
                <div class="form-group">
                    <label for="exampleInputFile"> Abstrak Laporan Tugas Akhir Final (PDF) </label>
                    <br>
                    <span> Paper (PDF)</span>
                    <input type="file" name="paper" accept=".pdf"  class="form-control">         
                </div>           
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" value="Simpan"> Save changes</button>
        </div>
            </form>
    </div>
    </div>
</div>
@stop

@push('scripts')
  
 

@endpush