routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $deadline = \App\deadline::where('status','=',1)->first();
    return redirect()->action('AuthController@login');
});

Route::get('/Login', 'AuthController@login')->name('login');
Route::post('/postlogin', 'AuthController@postlogin');
Route::get('/Logout', 'AuthController@logout');

Route::group(['middleware' => ['auth','checkRole:admin']], function () {
    Route::get('/Dashboard-Admin', 'DashboardController@admin');
    Route::get('/Mahasiswa', 'MahasiswaController@index');
    Route::post('/Mahasiswa/create', 'MahasiswaController@create');
    Route::get('/Mahasiswa/edit/{NIM}', 'MahasiswaController@edit');
    Route::post('/Mahasiswa/update/{NIM}', 'MahasiswaController@update');
    Route::get('/Mahasiswa/delete/{NIM}', 'MahasiswaController@delete');
    Route::get('/Mahasiswa/CreateUser', 'MahasiswaController@createUserMahasiswa');

    Route::get('/Dosen/Create', 'DosenController@create');
    Route::get('/Dosen/edit/{kode_dosen}', 'DosenController@edit');
    Route::post('/Dosen/{kode_dosen}/updateAdmin', 'DosenController@updateAdmin');
    Route::get('/Dosen/delete/{kode_dosen}', 'DosenController@delete');
    Route::post('/Dosen/Store', 'DosenController@store');
    Route::get('/Dosen/CreateUser', 'DosenController@createUserDosen');

    Route::resource('BAB', 'BabController');
    Route::resource('SubBab', 'SubBabController');
    Route::resource('Minggu-Bimbingan', 'MinggubimbinganController');
    Route::resource('Deadline', 'DeadlineController');
    Route::resource('Poin-Penilaian', 'PoinPenilaianController');
    Route::resource('Poin-Penilaian-Laporan', 'PoinPenilaianLaporanController');
    Route::resource('Jadwal-Sidang', 'JadwalSidangController');
});

Route::group(['middleware' => ['auth','checkRole:mhs']], function () {
    Route::get('/Mahasiswa/Beranda', 'DashboardController@mahasiswa');
    Route::get('/Mahasiswa/Profile', 'MahasiswaController@profile');
    Route::post('/Mahasiswa/{NIM}/update', 'MahasiswaController@update'); 
    Route::post('/Mahasiswa/changePassword', 'MahasiswaController@changePassword');

    Route::post('/Proposal/Store/Finalisasi', 'proposal_taController@storefinalisasi');

    Route::get('/Proposal/TA/R0', 'proposal_taController@createR0');
    Route::get('/Proposal/TA/R1', 'proposal_taController@createR1');
    Route::post('/Proposal/Store/DataProposal', 'proposal_taController@storeDataProposal');
    Route::post('/Proposal/Store/Abstrak', 'proposal_taController@storeAbstrak');
    Route::post('/Proposal/Store/Pendahuluan', 'proposal_taController@storePendahuluan');
    Route::post('/Proposal/Store/TinjauanPustaka', 'proposal_taController@storeTinjauanPustaka');
    Route::post('/Proposal/Store/MetodePelaksanaan', 'proposal_taController@storeMetodePelaksanaan');
    Route::post('/Proposal/Store/BiayaJadwal', 'proposal_taController@storeBiayaJadwal');
    Route::post('/Proposal/Store/DaftarPustaka', 'proposal_taController@storeDaftarPustaka');
    Route::post('/Proposal/Store/JustifikasiAnggaran', 'proposal_taController@storeJustifikasiAnggaran');
    Route::post('/Proposal/Store/UploadFile', 'proposal_taController@storeUploadFile');
    Route::post('/Proposal/Store/GambaranTeknologi', 'proposal_taController@storeGambaranTeknologi');

    Route::get('/Laporan/TA', 'laporanTAController@create');
    Route::post('/LaporanTA/Store', 'laporanTAController@store');

    Route::get('Bimbingan', 'BimbinganController@index');
    Route::get('Bimbingan/create', 'BimbinganController@create');
    Route::post('Bimbingan/store', 'BimbinganController@store');

    Route::resource('Paper', 'paperController');
    
});

Route::group(['middleware' => ['auth','checkRole:dsn']], function () {
    Route::get('/Dosen/Beranda', 'DosenController@index');
    Route::get('/Dosen/Profile', 'DosenController@profile');
    Route::post('/Dosen/{kode_dosen}/update', 'DosenController@update');
    Route::post('/Dosen/changePassword', 'DosenController@changePassword');
    Route::get('/Bimbingan/Verifikasi', 'BimbinganController@verifikasi');
    Route::get('/Bimbingan/Rekap', 'BimbinganController@rekap');
    Route::get('/Bimbingan/ListVerifikasi', 'BimbinganController@ListVerifikasi');
    Route::post('/Bimbingan/saveBimbingan', 'BimbinganController@saveBimbingan');
    //// laporan ta
    Route::get('/Laporan/Penilaian/List-Mahasiswa', 'laporanTAController@listMahasiswa');
    Route::get('/Laporan/Penilaian/{nim}', 'laporanTAController@penilaianLaporan');
    Route::post('/Laporan/Penilaian/simpan', 'laporanTAController@saveNilaiLaporan');
    Route::post('/Laporan/Revisi/simpan', 'laporanTAController@saveRevisiLaporan');
    Route::post('/Laporan/Revisi/finalisasi', 'laporanTAController@finalisasiRevisiLaporan');
    Route::get('/Laporan/Nilai/List-Mahasiswa', 'laporanTAController@listMahasiswapanitia');
    Route::get('/Laporan/Download/{nama}', 'laporanTAController@downloadfile');
    Route::post('/Unlock/Laporan', 'laporanTAController@unlocknilailaporan');
    Route::get('/Laporan/Nilai/{nim}', 'laporanTAController@detailNilaiLaporan');
    Route::get('/Laporan/Penilaian/Panitia/{nim}/{kode_dosen}', 'laporanTAController@penilaianLaporanPanitia');
    ////sidang ta
    Route::get('/SidangTA/Penilaian/List-Mahasiswa', 'sidangTAController@listMahasiswa');
    Route::get('/SidangTA/Penilaian/{nim}', 'sidangTAController@penilaianSidangTA');
    Route::post('/Laporan/Penilaian/SidangTA/simpan', 'sidangTAController@saveNilaiSidang');
    Route::post('/SidangTA/finalisasi', 'sidangTAController@finalisasiNilaiSidang');
    Route::get('/SidangTA/Nilai-Akhir/{nim}', 'sidangTAController@nilaiSidangAkhir');
    Route::get('/SidangTA/Nilai/List-Mahasiswa', 'sidangTAController@listMahasiswapanitia');
    Route::get('/SidangTA/Penilaian/Panitia/{nim}/{kode_dosen}', 'sidangTAController@penilaianSidangTAPanitia');

    //NIlai PKM publikasi
    Route::resource('/Nilai-PKM-Publikasi', 'nilaiPKMPublikasiController');

    //Paper
    Route::get('/Mahasiswa-Paper', 'paperController@listMahasiswa');
    Route::post('/Paper/saveStatusPaper', 'paperController@saveStatusPaper');
    
});

app/poinPenilaianLaporan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class poinPenilaianLaporan extends Model
{
    protected $table = 'poin_penilaianlaporan';
    protected $fillable = ['poin_penilaian','deskripsi','bobot','ket','jenis'];

    
    public function mahasiswa()
    {
        return $this->belongsToMany('App\Mahasiswa','nim');
    }
    
}

app/Http/Controllers/poinPenilaianLaporanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\poinPenilaianLaporan;

class poinPenilaianLaporanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $PoinPenilaianLaporan = poinPenilaianLaporan::all();
        return view('PoinPenilaianLaporan.index',compact('PoinPenilaianLaporan'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //$PoinPenilaianLaporan = poinPenilaianLaporan::create($request->all());
        $jenis = implode(",", $request->jenis);
        $PoinPenilaianLaporan = new poinPenilaianLaporan;
        $PoinPenilaianLaporan->poin_penilaian = $request->poin_penilaian;
        $PoinPenilaianLaporan->deskripsi = $request->deskripsi;
        $PoinPenilaianLaporan->bobot = $request->bobot;
        $PoinPenilaianLaporan->ket = $request->ket;
        $PoinPenilaianLaporan->jenis = $jenis;
        $PoinPenilaianLaporan->save();
        //dd($request->all()); 
        return redirect('/Poin-Penilaian-Laporan')->with('sukses','Data Berhasil Disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $PoinPenilaianLaporan = poinPenilaianLaporan::find($id);
        $jenis = explode(",",$PoinPenilaianLaporan->jenis);
        return view('PoinPenilaianLaporan.edit',compact('PoinPenilaianLaporan','jenis'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $jenis = implode(",", $request->jenis);
        $PoinPenilaianLaporan = poinPenilaianLaporan::find($id);
        $PoinPenilaianLaporan->poin_penilaian = $request->poin_penilaian;
        $PoinPenilaianLaporan->deskripsi = $request->deskripsi;
        $PoinPenilaianLaporan->bobot = $request->bobot;
        $PoinPenilaianLaporan->ket = $request->ket;
        $PoinPenilaianLaporan->jenis = $jenis;
        $PoinPenilaianLaporan->save();
        
        return redirect('/Poin-Penilaian-Laporan')->with('sukses','Data Berhasil Diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $PoinPenilaianLaporan = poinPenilaianLaporan::find($id);
        $PoinPenilaianLaporan->delete();
        return redirect('/Poin-Penilaian-Laporan')->with('sukses','Data Berhasil Dihapus');
    }
}

resources/views/PoinPenilaianLaporan/edit.blade.php
@extends('Layout.master')

@section('title','Ubah Poin Penilaian')

@section('content')
    @if (session('sukses'))
    <div class="alert alert-success" role="alert">
        {{session('sukses')}}
    </div>        
    @endif
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
        <div class="row mb-2">
            <div class="offset-2">
                <h1 class="m-0 text-dark">Edit Poin Penilaian</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
            <ol class="breadcrumb float-sm-left" style="margin-top:7px;">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active" >Poin Penilaian</li>
            </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
        
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <section class="col-8 offset-2">
            <!-- Custom tabs (Charts with tabs)-->
            <div class="card">
                <div class="card-body">
                    <div class="col-12">
                        <form action="{{ route('Poin-Penilaian-Laporan.update', $PoinPenilaianLaporan->id) }}" method="POST">
                            
                            <input type="hidden" name="_method" value="PUT">                 
                            {{csrf_field()}}
                            <div class="form-group">
                                <label>Poin Penilaian</label>
                                <input type="text" name="poin_penilaian" class="form-control" value="{{$PoinPenilaianLaporan->poin_penilaian}}">
                            </div>
                            <div class="form-group">
                                <label>Deskripsi</label>
                                <textarea name="deskripsi" class="form-control" id="deskripsiPoinLaporan">{{$PoinPenilaianLaporan->deskripsi}}</textarea>
                            </div>

                            <div class="form-group">
                                <label>Bobot</label>
                                <input type="text" name="bobot" class="form-control" value="{{$PoinPenilaianLaporan->bobot}}">
                            </div>
                            <div class="form-group">
                                <label>Keterangan Nilai</label>
                                <Select class="form-control" name='ket'>
                                    <option value="Depan" @if($PoinPenilaianLaporan->ket == "Depan") Selected @endif >Halaman Depan</option>
                                    <option value="BAB 1" @if($PoinPenilaianLaporan->ket == "BAB 1") Selected @endif >BAB 1</option>
                                    <option value="BAB 2" @if($PoinPenilaianLaporan->ket == "BAB 2") Selected @endif >BAB 2</option>
                                    <option value="BAB 3" @if($PoinPenilaianLaporan->ket == "BAB 3") Selected @endif >BAB 3</option>
                                    <option value="BAB 4" @if($PoinPenilaianLaporan->ket == "BAB 4") Selected @endif >BAB 4</option>
                                    <option value="BAB 5" @if($PoinPenilaianLaporan->ket == "BAB 5") Selected @endif >BAB 5</option>
                                    <option value="Lampiran" @if($PoinPenilaianLaporan->ket == "Lampiran") Selected @endif >Lampiran</option>
                                </Select>
                            </div>

                            <div class="form-group">
                                <label> Jenis Judul TA</label>
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" name="jenis[]" value="1" class="custom-control-input" id="Hardware" @if(in_array("1",$jenis)) checked @endif>
                                    <label class="custom-control-label" for="Hardware">Hardware</label>
                                </div>
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" name="jenis[]" value="2" class="custom-control-input" id="Software" @if(in_array("2",$jenis)) checked @endif>
                                    <label class="custom-control-label" for="Software">Software</label>
                                </div>
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" name="jenis[]" value="3" class="custom-control-input" id="SoftwareHardware" @if(in_array("3",$jenis)) checked @endif>
                                    <label class="custom-control-label" for="SoftwareHardware">Software+Hardware</label>
                                </div>
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" name="jenis[]" value="4" class="custom-control-input" id="Antenna/Filter" @if(in_array("4",$jenis)) checked @endif>
                                    <label class="custom-control-label" for="Antenna/Filter">Antenna/Filter</label>
                                </div>
                            </div>

                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary btn-warning" value="Simpan"> Update</button>
                                </div>
                        </form>
                    </div>
                </div><!-- /.card-body -->
            </div>
            <!-- /.card -->

            </section>
            <!-- /.Left col -->
        </div>
        <!-- /.row (main row) -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

@push('scripts')
    <script src="https://cdn.ckeditor.com/4.11.4/standard/ckeditor.js"></script>
    <script src="{{asset('js/ckeditor.js')}}"></script>
@endpush

resources/views/PoinPenilaianLaporan/index.blade.php
@extends('Layout.master')

@section('title','Poin Penilaian Laporan')

@section('content')
@if (session('sukses'))
    <div class="col-8" style="margin:10px auto;">
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{session('sukses')}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>       
@endif
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="">
        <h1 class="m-0 text-dark">Dashboard</h1>
        </div><!-- /.col -->
        <div class="col-sm-6" style="margin-top:7px;">
        <ol class="breadcrumb float-sm-left">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item">Poin Penilaian Laporan</li>
        </ol>
        </div><!-- /.col -->
    </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
    
    <!-- Main row -->
    <div class="row">
        <!-- Left col -->
        <section class="col-12">
        <!-- Custom tabs (Charts with tabs)-->
        <div class="card">
            <div class="card-header">
            <h3 class="card-title p-3">
                <i class="fa fa-pie-chart mr-1"></i>
                Data Poin Penilaian Laporan
            </h3>
            </div><!-- /.card-header -->
            <div class="card-body" style="padding:30px">
                <div class="row">
                    <div class="col-10">
                        <h1>Data Poin Penilaian</h1>
                    </div>
                    
                    <div class="col-2">
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary float-right" data-toggle="modal" data-target="#exampleModal" style="margin-right:40px;">
                            Tambah
                        </button>
                    </div>              
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-striped table-responsive" id="poin">
                            <thead >
                                <tr>
                                    <td>Poin Penilaian</td>
                                    <td>Deskripsi</td>
                                    <td>Bobot</td>
                                    <td>Keterangan</td>
                                    <td style="max-width:15%">Jenis</td>
                                    <td>Action</td>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($PoinPenilaianLaporan as $item)
                                <tr>
                                    <td>{{ $item->poin_penilaian }}</td>
                                    <td>{!! $item->deskripsi !!}</td>
                                    <td>{{ $item->bobot }}</td>
                                    <td>{{ $item->ket }}</td>
                                    <td>
                                        @php
                                            $jenis = explode(",",$item->jenis);
                                            if(in_array("1",$jenis)){ echo "- Hardware<br>";}
                                            if(in_array("2",$jenis)){ echo "- Software<br>";}
                                            if(in_array("3",$jenis)){ echo "- Hardware + Software<br>";}
                                            if(in_array("4",$jenis)){ echo "- Antenna / Filter <br>";}
                                        @endphp
                                    </td>
                                    <td>
                                        <a href="{{ route('Poin-Penilaian-Laporan.edit',$item->id) }}" class="btn btn-warning">Edit</a>
                                        <form action="{{ route('Poin-Penilaian-Laporan.destroy', $item->id)}}" method="post">
                                                <input type="hidden" name="_method" value="DELETE">                 
                                                {{csrf_field()}}
                                            <button class="btn btn-danger" type="submit" onclick="return confirm('Yakin anda akan menghapus data ini ?')">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        
                    </div>
                </div>
            </div><!-- /.card-body -->
        </div>
        <!-- /.card -->

        </section>
        <!-- /.Left col -->
        
    </div>
    <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->


<!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('Poin-Penilaian-Laporan.store') }}" method="POST">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label>Poin Penilaian</label>
                        <input type="text" name="poin_penilaian" class="form-control">
                    </div>
                    <div class="form-group">
                            <label>Deskripsi</label>
                            <textarea name="deskripsi" class="form-control" id="deskripsiPoinLaporan"></textarea>
                        </div>
                    <div class="form-group">
                            <label>Bobot</label>
                            <input type="text" name="bobot" class="form-control">
                        </div>
                    <div class="form-group">
                        <label>Keterangan Nilai</label>
                        <Select class="form-control" name='ket'>
                            <option value="Depan">Halaman Depan</option>
                            <option value="BAB 1">BAB 1</option>
                            <option value="BAB 2">BAB 2</option>
                            <option value="BAB 3">BAB 3</option>
                            <option value="BAB 4">BAB 4</option>
                            <option value="BAB 5">BAB 5</option>
                            <option value="Lampiran">Lampiran</option>
                        </Select>
                    </div>
                    <div class="form-group">
                        <label> Jenis Judul TA</label>
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" name="jenis[]" value="1" class="custom-control-input" id="Hardware">
                            <label class="custom-control-label" for="Hardware">Hardware</label>
                        </div>
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" name="jenis[]" value="2" class="custom-control-input" id="Software">
                            <label class="custom-control-label" for="Software">Software</label>
                        </div>
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" name="jenis[]" value="3" class="custom-control-input" id="SoftwareHardware">
                            <label class="custom-control-label" for="SoftwareHardware">Software+Hardware</label>
                        </div>
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" name="jenis[]" value="4" class="custom-control-input" id="Antenna/Filter">
                            <label class="custom-control-label" for="Antenna/Filter">Antenna/Filter</label>
                        </div>
                    </div>
                          
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary" value="Simpan"> Save changes</button>
            </div>
                </form>
        </div>
        </div>
    </div>
     
@endsection

@push('scripts')
    <script>
        $(function () {
            $("#poin").DataTable( {
                "order": [[ 3, "desc" ]]
            } );
        });
    </script>
    <script src="https://cdn.ckeditor.com/4.11.4/standard/ckeditor.js"></script>
    <script src="{{asset('js/ckeditor.js')}}"></script>
@endpush