routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $deadline = \App\deadline::where('status','=',1)->first();
    return redirect()->action('AuthController@login');
});

Route::get('/Login', 'AuthController@login')->name('login');
Route::post('/postlogin', 'AuthController@postlogin');
Route::get('/Logout', 'AuthController@logout');

Route::group(['middleware' => ['auth','checkRole:admin']], function () {
    Route::get('/Dashboard-Admin', 'DashboardController@admin');
    Route::get('/Mahasiswa', 'MahasiswaController@index');
    Route::post('/Mahasiswa/create', 'MahasiswaController@create');
    Route::get('/Mahasiswa/edit/{NIM}', 'MahasiswaController@edit');
    Route::post('/Mahasiswa/update/{NIM}', 'MahasiswaController@update');
    Route::get('/Mahasiswa/delete/{NIM}', 'MahasiswaController@delete');
    Route::get('/Mahasiswa/CreateUser', 'MahasiswaController@createUserMahasiswa');

    Route::get('/Dosen/Create', 'DosenController@create');
    Route::get('/Dosen/edit/{kode_dosen}', 'DosenController@edit');
    Route::post('/Dosen/{kode_dosen}/updateAdmin', 'DosenController@updateAdmin');
    Route::get('/Dosen/delete/{kode_dosen}', 'DosenController@delete');
    Route::post('/Dosen/Store', 'DosenController@store');
    Route::get('/Dosen/CreateUser', 'DosenController@createUserDosen');

    Route::resource('BAB', 'BabController');
    Route::resource('SubBab', 'SubBabController');
    Route::resource('Minggu-Bimbingan', 'MinggubimbinganController');
    Route::resource('Deadline', 'DeadlineController');
    Route::resource('Poin-Penilaian', 'PoinPenilaianController');
    Route::resource('Poin-Penilaian-Laporan', 'PoinPenilaianLaporanController');
    Route::resource('Jadwal-Sidang', 'JadwalSidangController');
});

Route::group(['middleware' => ['auth','checkRole:mhs']], function () {
    Route::get('/Mahasiswa/Beranda', 'DashboardController@mahasiswa');
    Route::get('/Mahasiswa/Profile', 'MahasiswaController@profile');
    Route::post('/Mahasiswa/{NIM}/update', 'MahasiswaController@update'); 
    Route::post('/Mahasiswa/changePassword', 'MahasiswaController@changePassword');

    Route::post('/Proposal/Store/Finalisasi', 'proposal_taController@storefinalisasi');

    Route::get('/Proposal/TA/R0', 'proposal_taController@createR0');
    Route::get('/Proposal/TA/R1', 'proposal_taController@createR1');
    Route::post('/Proposal/Store/DataProposal', 'proposal_taController@storeDataProposal');
    Route::post('/Proposal/Store/Abstrak', 'proposal_taController@storeAbstrak');
    Route::post('/Proposal/Store/Pendahuluan', 'proposal_taController@storePendahuluan');
    Route::post('/Proposal/Store/TinjauanPustaka', 'proposal_taController@storeTinjauanPustaka');
    Route::post('/Proposal/Store/MetodePelaksanaan', 'proposal_taController@storeMetodePelaksanaan');
    Route::post('/Proposal/Store/BiayaJadwal', 'proposal_taController@storeBiayaJadwal');
    Route::post('/Proposal/Store/DaftarPustaka', 'proposal_taController@storeDaftarPustaka');
    Route::post('/Proposal/Store/JustifikasiAnggaran', 'proposal_taController@storeJustifikasiAnggaran');
    Route::post('/Proposal/Store/UploadFile', 'proposal_taController@storeUploadFile');
    Route::post('/Proposal/Store/GambaranTeknologi', 'proposal_taController@storeGambaranTeknologi');

    Route::get('/Laporan/TA', 'laporanTAController@create');
    Route::post('/LaporanTA/Store', 'laporanTAController@store');

    Route::get('Bimbingan', 'BimbinganController@index');
    Route::get('Bimbingan/create', 'BimbinganController@create');
    Route::post('Bimbingan/store', 'BimbinganController@store');

    Route::resource('Paper', 'paperController');
    
});

Route::group(['middleware' => ['auth','checkRole:dsn']], function () {
    Route::get('/Dosen/Beranda', 'DosenController@index');
    Route::get('/Dosen/Profile', 'DosenController@profile');
    Route::post('/Dosen/{kode_dosen}/update', 'DosenController@update');
    Route::post('/Dosen/changePassword', 'DosenController@changePassword');
    Route::get('/Bimbingan/Verifikasi', 'BimbinganController@verifikasi');
    Route::get('/Bimbingan/Rekap', 'BimbinganController@rekap');
    Route::get('/Bimbingan/ListVerifikasi', 'BimbinganController@ListVerifikasi');
    Route::post('/Bimbingan/saveBimbingan', 'BimbinganController@saveBimbingan');
    //// laporan ta
    Route::get('/Laporan/Penilaian/List-Mahasiswa', 'laporanTAController@listMahasiswa');
    Route::get('/Laporan/Penilaian/{nim}', 'laporanTAController@penilaianLaporan');
    Route::post('/Laporan/Penilaian/simpan', 'laporanTAController@saveNilaiLaporan');
    Route::post('/Laporan/Revisi/simpan', 'laporanTAController@saveRevisiLaporan');
    Route::post('/Laporan/Revisi/finalisasi', 'laporanTAController@finalisasiRevisiLaporan');
    Route::get('/Laporan/Nilai/List-Mahasiswa', 'laporanTAController@listMahasiswapanitia');
    Route::get('/Laporan/Download/{nama}', 'laporanTAController@downloadfile');
    Route::post('/Unlock/Laporan', 'laporanTAController@unlocknilailaporan');
    Route::get('/Laporan/Nilai/{nim}', 'laporanTAController@detailNilaiLaporan');
    Route::get('/Laporan/Penilaian/Panitia/{nim}/{kode_dosen}', 'laporanTAController@penilaianLaporanPanitia');
    ////sidang ta
    Route::get('/SidangTA/Penilaian/List-Mahasiswa', 'sidangTAController@listMahasiswa');
    Route::get('/SidangTA/Penilaian/{nim}', 'sidangTAController@penilaianSidangTA');
    Route::post('/Laporan/Penilaian/SidangTA/simpan', 'sidangTAController@saveNilaiSidang');
    Route::post('/SidangTA/finalisasi', 'sidangTAController@finalisasiNilaiSidang');
    Route::get('/SidangTA/Nilai-Akhir/{nim}', 'sidangTAController@nilaiSidangAkhir');
    Route::get('/SidangTA/Nilai/List-Mahasiswa', 'sidangTAController@listMahasiswapanitia');
    Route::get('/SidangTA/Penilaian/Panitia/{nim}/{kode_dosen}', 'sidangTAController@penilaianSidangTAPanitia');

    //NIlai PKM publikasi
    Route::resource('/Nilai-PKM-Publikasi', 'nilaiPKMPublikasiController');

    //Paper
    Route::get('/Mahasiswa-Paper', 'paperController@listMahasiswa');
    Route::post('/Paper/saveStatusPaper', 'paperController@saveStatusPaper');
    
});

app/nilaiPKMPublikasi.php
<?php

namespace App;
use \App\poinPublikasi;
use \App\poinPKM;
use \App\Mahasiswa;

use Illuminate\Database\Eloquent\Model;

class nilaiPKMPublikasi extends Model
{
    protected $table = 'nilai_pkmpublikasi';
    protected $fillable = ['nim','poin_pkm_id','poin_publikasi_id'];

    public function poinPKM()
    {
        return $this->belongsTo(poinPKM::class, 'poin_pkm_id');
    }

    public function poinPublikasi()
    {
        return $this->belongsTo(poinPublikasi::class, 'poin_publikasi_id');
    }

}

app/Http/Controllers/nilaiPKMPublikasiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use \App\nilaiPKMPublikasi;
use \App\poinPKM;
use \App\poinPublikasi;
use \App\Mahasiswa;

class nilaiPKMPublikasiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $mahasiswa = DB::table('mahasiswa')
            ->leftJoin('nilai_pkmpublikasi', 'nilai_pkmpublikasi.nim', '=', 'mahasiswa.nim')
            //->leftJoin('jadwal_sidang', 'jadwal_sidang.nim', '=', 'mahasiswa.nim')
            ->orderBy('mahasiswa.NIM', 'ASC')
            ->get();

        return view('NilaiPKMPublikasi.index',compact('mahasiswa'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $nilai_pkmpublikasi = nilaiPKMPublikasi::where('nim','=',$id)->first();
        if (isset($nilai_pkmpublikasi)) {
            $mhs = Mahasiswa::where('NIM','=',$id)->first();
            $poin_pkm = poinPKM::all();
            $poin_publikasi = poinPublikasi::all();
            return view('NilaiPKMPublikasi.edit', compact('mhs','poin_pkm','poin_publikasi','nilai_pkmpublikasi'));
        }else{
            $mhs = Mahasiswa::where('NIM','=',$id)->first();
            $poin_pkm = poinPKM::all();
            $poin_publikasi = poinPublikasi::all();
            return view('NilaiPKMPublikasi.edit', compact('mhs','poin_pkm','poin_publikasi'));
        }
        

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $nilai_pkmpublikasi = nilaiPKMPublikasi::updateOrCreate([
            'nim'   => $request->nim,
        ],[
            'poin_pkm_id'       => $request->poin_pkm_id,
            'poin_publikasi_id' => $request->poin_publikasi_id
            
        ]);
        if ($nilai_pkmpublikasi) {
            return redirect('/Nilai-PKM-Publikasi')->with('sukses','Berhasil Ubah/Simpan Data');
        }else{
            return redirect('/Nilai-PKM-Publikasi')->with('gagal','Gagal Ubah/Simpan Data');
        }
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/NilaiPKMPublikasi/edit.blade.php
@extends('Layout.master')

@section('title','Ubah Nilai PKM dan Publikasi Ilmilah')

@section('navbar')
<!-- Navbar -->
<nav class="main-header navbar navbar-expand bg-primary navbar-dark ">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="{{url('/Dosen/Beranda')}}" class="nav-link">Beranda</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="{{url('/Dosen/Profile')}}" class="nav-link">Profile</a>
    </li>
  </ul>

</nav>
<!-- /.navbar -->
@stop

@section('content')
  @if (session('sukses'))
  <div class="alert alert-success col-md-6 alert-fixed" role="alert" >
      {{session('sukses')}}
  </div>
  @elseif (session('gagal'))
  <div class="alert alert-danger col-md-6 alert-fixed" role="alert" >
      {{session('gagal')}}
  </div>
  @endif
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
        <div class="row mb-2" style="padding-left:20px">
            <div class="">
                <h1 class="m-0 text-dark">Daftar Mahasiswa Nilai PKM dan Publikasi</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
            <ol class="breadcrumb float-sm-left" style="margin-top:7px;">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item">Nilai</li>
                <li class="breadcrumb-item">PKM dan Publikasi</li>
                <li class="breadcrumb-item active">Ubah</li>
            </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
        
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <section class="col-12">
            <!-- Custom tabs (Charts with tabs)-->
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('Nilai-PKM-Publikasi.update',$mhs->NIM ) }}" method="POST">
                        <input type="hidden" name="_method" value="PUT">                 
                        {{csrf_field()}}
                        <div class="form-group">
                            <label>NIM</label>
                            <input type="text" name="nim" class="form-control" value="{{$mhs->NIM}}" readonly>
                        </div>
                        <div class="form-group">
                            <label>Nama</label>
                            <input type="text" name="nama" class="form-control" value="{{$mhs->nama}}" readonly>
                        </div>

                        <h4>Nilai PKM</h4>

                        @foreach ($poin_pkm as $item)
                            <div class="custom-control custom-radio">
                                <input type="radio" id="{{$item->id}}" name="poin_pkm_id" class="custom-control-input" value="{{$item->id}}" 
                                @if (isset($nilai_pkmpublikasi))
                                    @if ($nilai_pkmpublikasi->poin_pkm_id == $item->id) checked @endif
                                @endif >
                                <label class="custom-control-label" for="{{$item->id}}">{{$item->nama_pkm}} {{$item->bobot}}</label>
                            </div>
                        @endforeach
                            <br>
                        <h4>Nilai Publikasi</h4>

                        @foreach ($poin_publikasi as $value)
                            <div class="custom-control custom-radio">
                                <input type="radio" id="publikasi_{{$value->id}}" name="poin_publikasi_id"  value="{{$value->id}}" class="custom-control-input" 
                                @if (isset($nilai_pkmpublikasi))
                                    @if ($nilai_pkmpublikasi->poin_publikasi_id == $value->id) checked @endif
                                @endif
                                >
                                <label class="custom-control-label" for="publikasi_{{$value->id}}">{{$value->nama_publikasi}} {{$value->bobot}}</label>
                            </div>
                        @endforeach

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-warning" value="Simpan"> Update</button>
                        </div>
                    </form>
                </div><!-- /.card-body -->
            </div>
            <!-- /.card -->

            </section>
            <!-- /.Left col -->
            
        </div>
        <!-- /.row (main row) -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

@push('scripts')    
    <script>
        $(function () {
            $("#listMhs_nilaiPKmpublikasi").DataTable( {
                "order": [[ 0, "asc" ]]
            } );
        });           

    </script>  
@endpush

resources/views/NilaiPKMPublikasi/index.blade.php
<?php 
use Illuminate\Support\Facades\DB;
?>
@extends('Layout.master')

@section('title','Nilai PKM dan Publikasi Ilmilah')

@section('navbar')
<!-- Navbar -->
<nav class="main-header navbar navbar-expand bg-primary navbar-dark ">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="{{url('/Dosen/Beranda')}}" class="nav-link">Beranda</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="{{url('/Dosen/Profile')}}" class="nav-link">Profile</a>
    </li>
  </ul>

</nav>
<!-- /.navbar -->
@stop

@section('content')
  @if (session('sukses'))
  <div class="alert alert-success col-md-6 alert-fixed" role="alert" >
      {{session('sukses')}}
  </div>
  @elseif (session('gagal'))
  <div class="alert alert-danger col-md-6 alert-fixed" role="alert" >
      {{session('gagal')}}
  </div>
  @endif
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
        <div class="row mb-2" style="padding-left:20px">
            <div class="">
                <h1 class="m-0 text-dark">Daftar Mahasiswa Nilai PKM dan Publikasi</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
            <ol class="breadcrumb float-sm-left" style="margin-top:7px;">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item">Nilai</li>
                <li class="breadcrumb-item active">PKM dan Publikasi</li>
            </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
        
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <section class="col-12">
            <!-- Custom tabs (Charts with tabs)-->
            <div class="card">
                <div class="card-body">
                    <table class="table table-responsive table-striped" id="listMhs_nilaiPKmpublikasi">
                        <thead class="thead-dark">
                           <th>NIM</th> <th>Nama</th> <th>Kelas </th> <th>Nilai PKM</th> <th>Nilai Publikasi Ilmiah</th> <th>Action</th> <th> Action </th> 
                        </thead>
                        <tbody>
                            
                            @foreach ($mahasiswa as $item)
                                @php
                                    //$nilai_pkmPublikasi = \App\nilaiPKMPublikasi::where('nim','=',$item->NIM)->first();
                                    $nilai_pkm = DB::table('nilai_pkmpublikasi')
                                        ->Join('poin_pkm', 'nilai_pkmpublikasi.poin_pkm_id', '=', 'poin_pkm.id')
                                        ->Where('nilai_pkmpublikasi.nim', '=',$item->NIM)
                                        ->first();
                                    $nilai_publikasi = DB::table('nilai_pkmpublikasi')
                                        ->Join('poin_publikasi', 'nilai_pkmpublikasi.poin_publikasi_id', '=', 'poin_publikasi.id')
                                        ->Where('nilai_pkmpublikasi.nim', '=',$item->NIM)
                                        ->first();
                                    //dd($nilai_pkmpublikasi);
                                @endphp
                                <tr>
                                    <td>{{$item->NIM}}</td>
                                    <td>{{$item->nama}}</td>
                                    <td>{{$item->kelas}}/{{$item->angkatan}}</td>
                                    <td><b>{{ $nilai_pkm->bobot or '' }}</b>  ({{ $nilai_pkm->nama_pkm or 'kosong' }})</td>
                                    <td><b>{{ $nilai_publikasi->bobot or '' }}</b> ( {{ $nilai_publikasi->nama_publikasi or 'kosong' }} )</td>
                                    <td><a href="{{ route('Nilai-PKM-Publikasi.edit',$item->NIM) }}" class="btn btn-warning">Edit</a></td>
                                    <td>
                                        <form action="{{ route('Nilai-PKM-Publikasi.destroy', $item->id)}}" method="post">
                                            <input type="hidden" name="_method" value="DELETE">                 
                                            {{csrf_field()}}
                                        <button class="btn btn-danger" type="submit" onclick="return confirm('Yakin anda akan menghapus data ini ?')">Delete</button>
                                    </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div><!-- /.card-body -->
            </div>
            <!-- /.card -->

            </section>
            <!-- /.Left col -->
            
        </div>
        <!-- /.row (main row) -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

@push('scripts')    
    <script>
        $(function () {
            $("#listMhs_nilaiPKmpublikasi").DataTable( {
                "order": [[ 0, "asc" ]]
            } );
        });           

    </script>  
@endpush